name: Update chart

on:
  workflow_dispatch:
  schedule:
      - cron: "0 5 * * *"

permissions:
  contents: write

jobs:
  update_chart:
    runs-on: ubuntu-latest
    outputs:
      time: ${{ steps.current_time.outputs.time }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v4
        with:
            python-version: "3.10"
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run notebook
        run: jupyter nbconvert --to notebook --execute --inplace bitcoin.ipynb

      - name: Current time
        id: current_time
        run: 
          echo "time=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Commit and push changes
        uses: giocaizzi/python-dev-actions/.github/actions/commit@main
        with:
            message: "Update chart:${{ steps.current_time.outputs.time }}"
            github-token: ${{ secrets.GITHUB_TOKEN }}